React issue 2
AppFolioOnboarding/image-sharer-achenqi pull request #9
Opened 2021-06-23 17:42 UTC by achenqi

2021-06-23 17:52 UTC, achenqi commented
![](https://github.trello.services/images/mini-trello-icon.png) [React Issue 2: Submit Feedback to backend](https://trello.com/c/OU3FVY18/420-react-issue-2-submit-feedback-to-backend)

2021-06-23 18:22 UTC, infiniteluke requested changes

2021-06-23 18:22 UTC, infiniteluke commented on app/models/feedback.rb
> +end
please make the commit message be descriptive of the code it adds. Reading it, I would not be able to tell which model you're talking about which makes it hard to grep/search for.

2021-06-23 18:22 UTC, infiniteluke commented on app/controllers/feedbacks_controller.rb
> +    @feedback = Feedback.new
Do we need this? does the `new.html.erb` template use it?

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/components/FeedbackForm.js
> +  handleSubmit()
What is the intention of calling handleSubmit here?

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/test/components/FeedbackForm.spec.js
> +  });
This is great that we have this test, we need more tests, though. We don't test that handleSubmit is called and we don't test that updating the input fields syncs with form values

2021-06-23 18:22 UTC, infiniteluke commented on test/fixtures/feedbacks.yml
> +# column: value
we should not add this file in this commit if we're going to remove it in a later one

2021-06-23 18:22 UTC, infiniteluke commented on test/models/feedback_test.rb
> +  # end
we should write a test that the `name`, and `comment` validation works

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/components/App.js
> +      <FeedbackForm post={post} />
This is close but it's a bit too low of an abstraction. I think we should pass something like `onSubmit` that is called in our `FeedbackForm` that will be called with the data to submit.

`onSubmit(formValues)`

in our App we can implement onSubmit with `post` and pass it as a prop

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/components/FeedbackForm.js
> +        this.setState({ response: true, responseMessage: 'Error submitting feedback' });
one of the best practices in react development is the "Use minimal state". This boolean is not necessary because we can use the existence of `responseMessage` to check if we should show a message or not.

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/components/FeedbackForm.js
> +        this.setState({ response: true, responseMessage: 'Error submitting feedback' });
perhaps we should store whether the response was an error or a success here?

2021-06-23 18:22 UTC, infiniteluke commented on app/javascript/image_sharing/components/FeedbackForm.js
> +      this.state.responseMessage === 'Successfully submitted feedback'
doing this check means we would have to change the message in two places if it ever changed. Can we establish whether the message is an error or not and store that separately from the message?

2021-06-24 18:44 UTC, infiniteluke commented on app/javascript/image_sharing/components/FeedbackForm.js
> +      responseSuccess: undefined
`responseSuccess: undefined` is not needed. If you exclude it, it will be `undefined`

2021-06-24 18:44 UTC, infiniteluke commented on app/javascript/image_sharing/test/components/FeedbackForm.spec.js
> +  it('should call handleSubmit when button is clicked', () => {
the name of this test isn't quite right

2021-06-24 18:44 UTC, infiniteluke commented on app/javascript/image_sharing/test/components/FeedbackForm.spec.js
> +  it('should call onSubmit when button is clicked with correct parameters', () => {
this doesn't actually click the button, so we should rename the test to reflect that we're calling `handleSubmit`

2021-06-24 23:39 UTC, infiniteluke approved these changes

2021-06-25 15:59 UTC, merged